version: '3.5'
services:
  db:
    image: 'postgres:13.2-alpine'
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: web
      POSTGRES_PASSWORD: 'F00B4r!'
    ports: ['5432:5432']
  db_wait:
    image: dadarek/wait-for-dependencies
    depends_on: [db]
    command: 'db:5432'
  web:
    build:
      context: ../
      dockerfile: docker/web/Dockerfile
    depends_on: [db_wait]
    environment:
      DB_HOST: db
      DB_PORT: '5432'
      DB_NAME: test
      DB_USERNAME: web
      DB_PASSWORD: 'F00B4r!'
    ports: ['8080:8080']
  background:
    build:
      context: ../
      dockerfile: docker/background/Dockerfile
    depends_on: [db_wait]
    environment:
      DB_HOST: db
      DB_PORT: '5432'
      DB_NAME: test
      DB_USERNAME: web
      DB_PASSWORD: 'F00B4r!'
      FETCH_LIMIT: 100
      POSTMARK_SERVER_TOKEN: '${POSTMARK_SERVER_TOKEN}'
      RENDER_EXTERNAL_URL: 'http://localhost:8080'
      SLEEP_SECS: 2

  # tasks:
  #   build: tasks/
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: '5432'
  #     DB_NAME: test
  #     DB_USERNAME: web
  #     DB_PASSWORD: 'F00B4r!'
